apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  type: ClusterIP
  selector:
      app: billing
  ports:
    - name: svc-port
      protocol: TCP
      port: 8080
      targetPort: http-web-svc